#! /usr/bin/env python3

import subprocess 
try:
	res = subprocess.Popen(['ping -t2 -c 4 192.168.1.1 &> /dev/null; echo $?'],shell=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
	out, err = res.communicate()
	out = out.rstrip()
	err = err.rstrip()
	print(f'general.connectivity() Out: {out}')
	print(f'general.connectivity() Err: {err}')
	if(out == "0"):
		print ('general.connectivity() Successful')
	print('general.connectivity() Failed')

except Exception(e):
	print('general.connectivity() Exception')

